### ISSUE TITLE
数据源和绑定数据是什么意思？

### ISSUE THREAD

**Issue by jinyangcruise** [stevefoxuser/html-table-editor-resizer#2]
先点个赞，很棒！

不太清楚设定数据源的本意是什么，好像现在是设定一个函数来执行？

绑定数据又是干啥的呢？

另外conf能不能暴露出来，可以设定其中的属性

**Comment by stevefoxuser** [comment]
@jinyangcruise  感谢点赞。
数据源设定上是从服务端取数据，绑定数据源就是把数据循环渲染在表格里。
当时还没做这个功能。
现在项目中用了这个功能发现太复杂，培训成本颇高。
于是就没有复制过来。
相关代码我去掉了，重新上传了。你就当无事发生过吧 ( :
至于conf，就直接在代码里改吧，cursorWidth是拖拽时光标有效的范围，minwidth是单元格最小的宽度。
